[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remmapings = [
    "contract-template/=lib/contract-template/src/",
    "@openzeppelin/=lib/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.21'
extra_output = ["devdoc", "userdoc", "storagelayout"]
evm_version = 'istanbul'
use_literal_content = true
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
ronin-mainnet = "https://api.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
localhost = "http://localhost:8545"

[fuzz]
runs = 256

[invariant]
runs = 256
